const reviewData = {
  alphabet: [
    {
      key: "a",
      title: "A",
      image: "assets/images/a.webp",
      alt: "A",
      wordAudio: "assets/audio/a.mp3",
      sentenceText: "A a apple ant.",
      sentenceAudio: "assets/audio/a-sentence.mp3",
    },
    {
      key: "b",
      title: "B",
      image: "assets/images/b.webp",
      alt: "B",
      wordAudio: "assets/audio/b.mp3",
      sentenceText: "B b ball banana.",
      sentenceAudio: "assets/audio/b-sentence.mp3",
    },
    {
      key: "c",
      title: "C",
      image: "assets/images/c.webp",
      alt: "C",
      wordAudio: "assets/audio/c.mp3",
      sentenceText: "C c cat car.",
      sentenceAudio: "assets/audio/c-sentence.mp3",
    },
    {
      key: "d",
      title: "D",
      image: "assets/images/d.webp",
      alt: "D",
      wordAudio: "assets/audio/d.mp3",
      sentenceText: "D d dog duck",
      sentenceAudio: "assets/audio/d-sentence.mp3",
    },
    {
      key: "e",
      title: "E",
      image: "assets/images/e.webp",
      alt: "E",
      wordAudio: "assets/audio/e.mp3",
      sentenceText: "E e elephant egg",
      sentenceAudio: "assets/audio/e-sentence.mp3",
    },
    {
      key: "f",
      title: "F",
      image: "assets/images/f.webp",
      alt: "F",
      wordAudio: "assets/audio/f.mp3",
      sentenceText: "F f fish flower",
      sentenceAudio: "assets/audio/f-sentence.mp3",
    },
    {
      key: "g",
      title: "G",
      image: "assets/images/g.webp",
      alt: "G",
      wordAudio: "assets/audio/g.mp3",
      sentenceText: "G g gorilla girl",
      sentenceAudio: "assets/audio/g-sentence.mp3",
    },
    {
      key: "h",
      title: "H",
      image: "assets/images/h.webp",
      alt: "H",
      wordAudio: "assets/audio/h.mp3",
      sentenceText: "H h hat house",
      sentenceAudio: "assets/audio/h-sentence.mp3",
    },
    {
      key: "i",
      title: "I",
      image: "assets/images/i.webp",
      alt: "I",
      wordAudio: "assets/audio/i.mp3",
      sentenceText: "I i igloo ink",
      sentenceAudio: "assets/audio/i-sentence.mp3",
    },
    {
      key: "j",
      title: "J",
      image: "assets/images/j.webp",
      alt: "J",
      wordAudio: "assets/audio/j.mp3",
      sentenceText: "J j juice jello",
      sentenceAudio: "assets/audio/j-sentence.mp3",
    },
    {
      key: "k",
      title: "K",
      image: "assets/images/k.webp",
      alt: "K",
      wordAudio: "assets/audio/k.mp3",
      sentenceText: "K k kangaroo kite",
      sentenceAudio: "assets/audio/k-sentence.mp3",
    },
    {
      key: "l",
      title: "L",
      image: "assets/images/l.webp",
      alt: "L",
      wordAudio: "assets/audio/l.mp3",
      sentenceText: "L l lion lemon",
      sentenceAudio: "assets/audio/l-sentence.mp3",
    },
    {
      key: "m",
      title: "M",
      image: "assets/images/m.webp",
      alt: "M",
      wordAudio: "assets/audio/m.mp3",
      sentenceText: "M m monkey milk",
      sentenceAudio: "assets/audio/m-sentence.mp3",
    },
    {
      key: "n",
      title: "N",
      image: "assets/images/n.webp",
      alt: "N",
      wordAudio: "assets/audio/n.mp3",
      sentenceText: "N n nose noodles",
      sentenceAudio: "assets/audio/n-sentence.mp3",
    },
    {
      key: "o",
      title: "O",
      image: "assets/images/o.webp",
      alt: "O",
      wordAudio: "assets/audio/o.mp3",
      sentenceText: "O o octopus orange",
      sentenceAudio: "assets/audio/o-sentence.mp3",
    },
    {
      key: "p",
      title: "P",
      image: "assets/images/p.webp",
      alt: "P",
      wordAudio: "assets/audio/p.mp3",
      sentenceText: "P p pig pizza",
      sentenceAudio: "assets/audio/p-sentence.mp3",
    },
    {
      key: "q",
      title: "Q",
      image: "assets/images/q.webp",
      alt: "Q",
      wordAudio: "assets/audio/q.mp3",
      sentenceText: "Q q queen quail",
      sentenceAudio: "assets/audio/q-sentence.mp3",
    },
    {
      key: "r",
      title: "R",
      image: "assets/images/r.webp",
      alt: "R",
      wordAudio: "assets/audio/r.mp3",
      sentenceText: "R r rabbit rainbow",
      sentenceAudio: "assets/audio/r-sentence.mp3",
    },
    {
      key: "s",
      title: "S",
      image: "assets/images/s.webp",
      alt: "S",
      wordAudio: "assets/audio/s.mp3",
      sentenceText: "S s snake sun",
      sentenceAudio: "assets/audio/s-sentence.mp3",
    },
    {
      key: "t",
      title: "T",
      image: "assets/images/t.webp",
      alt: "T",
      wordAudio: "assets/audio/t.mp3",
      sentenceText: "T t tiger tomato",
      sentenceAudio: "assets/audio/t-sentence.mp3",
    },
    {
      key: "u",
      title: "U",
      image: "assets/images/u.webp",
      alt: "U",
      wordAudio: "assets/audio/u.mp3",
      sentenceText: "U u umbrella unicorn",
      sentenceAudio: "assets/audio/u-sentence.mp3",
    },
    {
      key: "v",
      title: "V",
      image: "assets/images/v.webp",
      alt: "V",
      wordAudio: "assets/audio/v.mp3",
      sentenceText: "V v violin volcano",
      sentenceAudio: "assets/audio/v-sentence.mp3",
    },
    {
      key: "w",
      title: "W",
      image: "assets/images/w.webp",
      alt: "W",
      wordAudio: "assets/audio/w.mp3",
      sentenceText: "W w whale water",
      sentenceAudio: "assets/audio/w-sentence.mp3",
    },
    {
      key: "x",
      title: "X",
      image: "assets/images/x.webp",
      alt: "X",
      wordAudio: "assets/audio/x.mp3",
      sentenceText: "X x xylophone xenon",
      sentenceAudio: "assets/audio/x-sentence.mp3",
    },
    {
      key: "y",
      title: "Y",
      image: "assets/images/y.webp",
      alt: "Y",
      wordAudio: "assets/audio/y.mp3",
      sentenceText: "Y y yak yam",
      sentenceAudio: "assets/audio/y-sentence.mp3",
    },
    {
      key: "z",
      title: "Z",
      image: "assets/images/z.webp",
      alt: "Z",
      wordAudio: "assets/audio/z.mp3",
      sentenceText: "Z z zebra zero",
      sentenceAudio: "assets/audio/z-sentence.mp3",
    },
  ],
  small: [
    {
      key: "morning",
      title: "Morning",
      image: "assets/images/morning.webp",
      alt: "Morning",
      wordAudio: "assets/audio/morning.mp3",
      sentenceText: "Good morning!",
      sentenceAudio: "assets/audio/morning-sentence.mp3",
    },
    {
      key: "afternoon",
      title: "Afternoon",
      image: "assets/images/afternoon.webp",
      alt: "Afternoon",
      wordAudio: "assets/audio/afternoon.mp3",
      sentenceText: "Good afternoon!",
      sentenceAudio: "assets/audio/afternoon-sentence.mp3",
    },
  ],
  middle: [
    {
      key: "morning",
      title: "Morning",
      image: "assets/images/morning.webp",
      alt: "Morning",
      wordAudio: "assets/audio/morning.mp3",
      sentenceText: "Good morning!",
      sentenceAudio: "assets/audio/morning-sentence.mp3",
    },
    {
      key: "afternoon",
      title: "Afternoon",
      image: "assets/images/afternoon.webp",
      alt: "Afternoon",
      wordAudio: "assets/audio/afternoon.mp3",
      sentenceText: "Good afternoon!",
      sentenceAudio: "assets/audio/afternoon-sentence.mp3",
    },
    {
      key: "evening",
      title: "Evening",
      image: "assets/images/evening.webp",
      alt: "Evening",
      wordAudio: "assets/audio/evening.mp3",
      sentenceText: "Good evening!",
      sentenceAudio: "assets/audio/evening-sentence.mp3",
    },
    {
      key: "night",
      title: "Night",
      image: "assets/images/night.webp",
      alt: "Night",
      wordAudio: "assets/audio/night.mp3",
      sentenceText: "Good night!",
      sentenceAudio: "assets/audio/night-sentence.mp3",
    },
    {
      key: "teacher",
      title: "Teacher",
      image: "assets/images/teacher.webp",
      alt: "Teacher",
      wordAudio: "assets/audio/teacher.mp3",
      sentenceText: "Hello teacher!",
      sentenceAudio: "assets/audio/teacher-sentence.mp3",
    },
  ],
  big: [
    {
      key: "good-friend",
      title: "Good Friend",
      image: "assets/images/good-friend.webp",
      alt: "Good Friend",
      wordAudio: "assets/audio/good-friend.mp3",
      sentenceText: "He is my good friend!",
      sentenceAudio: "assets/audio/good-friend-sentence-1.mp3",
    },
    {
      key: "good-friend-1",
      title: "Good Friend",
      image: "assets/images/good-friend-1.webp",
      alt: "Good Friend",
      wordAudio: "assets/audio/good-friend.mp3",
      sentenceText: "She is my good friend!",
      sentenceAudio: "assets/audio/good-friend-sentence-2.mp3",
    },
    {
      key: "morning",
      title: "Morning",
      image: "assets/images/morning.webp",
      alt: "Morning",
      wordAudio: "assets/audio/morning.mp3",
      sentenceText: "Good morning!",
      sentenceAudio: "assets/audio/morning-sentence.mp3",
    },
    {
      key: "afternoon",
      title: "Afternoon",
      image: "assets/images/afternoon.webp",
      alt: "Afternoon",
      wordAudio: "assets/audio/afternoon.mp3",
      sentenceText: "Good afternoon!",
      sentenceAudio: "assets/audio/afternoon-sentence.mp3",
    },
    {
      key: "evening",
      title: "Evening",
      image: "assets/images/evening.webp",
      alt: "Evening",
      wordAudio: "assets/audio/evening.mp3",
      sentenceText: "Good evening!",
      sentenceAudio: "assets/audio/evening-sentence.mp3",
    },
    {
      key: "night",
      title: "Night",
      image: "assets/images/night.webp",
      alt: "Night",
      wordAudio: "assets/audio/night.mp3",
      sentenceText: "Good night!",
      sentenceAudio: "assets/audio/night-sentence.mp3",
    },
  ],
};
